import type { DemandConfirmed } from "@/lib/demand-display";
export type DuplicateLevel = "NEARLY_IDENTICAL" | "HIGHLY_SIMILAR" | "DIFFERENT";
export interface DuplicateCheckResult { level: DuplicateLevel; existingDemandId: string | null; differences: Array<{ field: string; from: string; to: string }> }
const MAKE_ALIASES: Record<string,string> = { מאזדה:"mazda",mazda:"mazda",טויוטה:"toyota",toyota:"toyota",יונדאי:"hyundai",hyundai:"hyundai" };
function norm(s:string|null|undefined){return(s??"").trim().toLowerCase()}
function normMake(s:string|null|undefined){const n=norm(s);return MAKE_ALIASES[n]??MAKE_ALIASES[s??""]??n}
function normModel(s:string|null|undefined){return norm(s).replace(/[\s\-_]/g,"")}
function fingerprint(c:DemandConfirmed){return{make:normMake(c.make),model:normModel(c.model),yearMin:c.yearMin??null,budgetMax:c.budgetMax??null,colors:[...(c.colorExclusions??[])].map(norm).sort()}}
function colorSetsEqual(a:string[],b:string[]){return a.length===b.length&&a.every((v,i)=>v===b[i])}
export function compareDemands(incoming:DemandConfirmed,existing:DemandConfirmed):{level:DuplicateLevel;differences:DuplicateCheckResult["differences"]}{const a=fingerprint(incoming),b=fingerprint(existing);const differences:DuplicateCheckResult["differences"]=[];if(!a.make||!b.make||a.make!==b.make)return{level:"DIFFERENT",differences};if(!a.model||!b.model||a.model!==b.model)return{level:"DIFFERENT",differences};if(a.yearMin!==b.yearMin)differences.push({field:"שנתון",from:String(b.yearMin??"—"),to:String(a.yearMin??"—")});if(a.budgetMax!==b.budgetMax)differences.push({field:"תקציב",from:b.budgetMax?String(b.budgetMax):"—",to:a.budgetMax?String(a.budgetMax):"—"});if(!colorSetsEqual(a.colors,b.colors))differences.push({field:"צבע",from:b.colors.join(", ")||"—",to:a.colors.join(", ")||"—"});if(!differences.length)return{level:"NEARLY_IDENTICAL",differences};const only=differences.every(d=>d.field==="שנתון"||d.field==="תקציב");return{level:only&&differences.length<=2?"HIGHLY_SIMILAR":"DIFFERENT",differences};}
export function findDuplicateDemand(incoming:DemandConfirmed,existingDemands:Array<{id:string;status:string;confirmedJson:unknown}>):DuplicateCheckResult{const active=existingDemands.filter(d=>["ACTIVE","PENDING_CONFIRMATION","DRAFT"].includes(d.status));let best:DuplicateCheckResult={level:"DIFFERENT",existingDemandId:null,differences:[]};for(const d of active){const confirmed=(d.confirmedJson??{}) as DemandConfirmed;if(!confirmed.make&&!confirmed.model)continue;const{level,differences}=compareDemands(incoming,confirmed);if(level==="NEARLY_IDENTICAL")return{level,existingDemandId:d.id,differences};if(level==="HIGHLY_SIMILAR"&&best.level!=="NEARLY_IDENTICAL")best={level,existingDemandId:d.id,differences};}return best;}
export function confirmedFromParsed(parsed:Record<string,unknown>):DemandConfirmed{const getVal=(f:unknown)=>f&&typeof f==="object"&&"value" in f?(f as {value:unknown}).value:f;const out:Partial<DemandConfirmed>={};const make=getVal(parsed.make),model=getVal(parsed.model),yearMin=getVal(parsed.yearMin),yearMax=getVal(parsed.yearMax),budgetMax=getVal(parsed.budgetMax);if(make!=null&&String(make).trim())out.make=String(make);if(model!=null&&String(model).trim())out.model=String(model);if(yearMin!=null&&Number.isFinite(Number(yearMin)))out.yearMin=Number(yearMin);if(yearMax!=null&&Number.isFinite(Number(yearMax)))out.yearMax=Number(yearMax);if(budgetMax!=null&&Number.isFinite(Number(budgetMax)))out.budgetMax=Number(budgetMax);if(Array.isArray(parsed.colorExclusions)&&parsed.colorExclusions.length)out.colorExclusions=parsed.colorExclusions as string[];return out as DemandConfirmed;}
