/**
 * Mobile /api/v1 error envelope. Web /api/* JSON is unchanged.
 * Machine state lives in `code`. `message` is display-only.
 */

export const V1_ERROR_CODES = {
  VALIDATION_INVALID_JSON: "VALIDATION_INVALID_JSON",
  VALIDATION_INVALID_REQUEST: "VALIDATION_INVALID_REQUEST",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",
  AUTH_REFRESH_EXPIRED: "AUTH_REFRESH_EXPIRED",
  PERMISSION_EMAIL_UNVERIFIED: "PERMISSION_EMAIL_UNVERIFIED",
  PERMISSION_DEALER_UNVERIFIED: "PERMISSION_DEALER_UNVERIFIED",
  PERMISSION_PRIVACY_INCOMPLETE: "PERMISSION_PRIVACY_INCOMPLETE",
  PERMISSION_ACCOUNT_SUSPENDED: "PERMISSION_ACCOUNT_SUSPENDED",
  PERMISSION_DEALER_DISABLED: "PERMISSION_DEALER_DISABLED",
  PERMISSION_FORBIDDEN: "PERMISSION_FORBIDDEN",
  PERMISSION_REAUTH_REQUIRED: "PERMISSION_REAUTH_REQUIRED",
  IDENTITY_LINK_REQUIRED: "IDENTITY_LINK_REQUIRED",
  IDENTITY_PROVIDER_TAKEN: "IDENTITY_PROVIDER_TAKEN",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  MATCH_VEHICLE_UNAVAILABLE: "MATCH_VEHICLE_UNAVAILABLE",
  MATCH_STALE_OPPORTUNITY: "MATCH_STALE_OPPORTUNITY",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  ENTITLEMENT_REQUIRED: "ENTITLEMENT_REQUIRED",
  REVEAL_ALLOWANCE_EXHAUSTED: "REVEAL_ALLOWANCE_EXHAUSTED",
  SERVER_INTERNAL: "SERVER_INTERNAL",
  AGENT_UNAVAILABLE: "AGENT_UNAVAILABLE",
  AGENT_TIMEOUT: "AGENT_TIMEOUT",
  MEDIA_UNAVAILABLE: "MEDIA_UNAVAILABLE",
} as const;

export type V1ErrorCode = (typeof V1_ERROR_CODES)[keyof typeof V1_ERROR_CODES];

export const V1_STATUS_BY_CODE: Record<V1ErrorCode, number> = {
  VALIDATION_INVALID_JSON: 400,
  VALIDATION_INVALID_REQUEST: 400,
  VALIDATION_FAILED: 422,
  AUTH_UNAUTHENTICATED: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_REVOKED: 401,
  AUTH_REFRESH_EXPIRED: 401,
  PERMISSION_EMAIL_UNVERIFIED: 403,
  PERMISSION_DEALER_UNVERIFIED: 403,
  PERMISSION_PRIVACY_INCOMPLETE: 403,
  PERMISSION_ACCOUNT_SUSPENDED: 403,
  PERMISSION_DEALER_DISABLED: 403,
  PERMISSION_FORBIDDEN: 403,
  PERMISSION_REAUTH_REQUIRED: 403,
  IDENTITY_LINK_REQUIRED: 409,
  IDENTITY_PROVIDER_TAKEN: 409,
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_CONFLICT: 409,
  MATCH_VEHICLE_UNAVAILABLE: 409,
  MATCH_STALE_OPPORTUNITY: 409,
  RATE_LIMIT_EXCEEDED: 429,
  ENTITLEMENT_REQUIRED: 402,
  REVEAL_ALLOWANCE_EXHAUSTED: 402,
  SERVER_INTERNAL: 500,
  AGENT_UNAVAILABLE: 503,
  AGENT_TIMEOUT: 504,
  MEDIA_UNAVAILABLE: 503,
};

const DEFAULT_MESSAGE_HE: Record<V1ErrorCode, string> = {
  VALIDATION_INVALID_JSON: "הבקשה אינה תקינה.",
  VALIDATION_INVALID_REQUEST: "הבקשה אינה תקינה.",
  VALIDATION_FAILED: "חלק מהשדות אינם תקינים.",
  AUTH_UNAUTHENTICATED: "נדרשת התחברות.",
  AUTH_TOKEN_EXPIRED: "פג תוקף החיבור. התחבר מחדש.",
  AUTH_TOKEN_REVOKED: "החיבור בוטל.",
  AUTH_REFRESH_EXPIRED: "פג תוקף החיבור. התחבר מחדש.",
  PERMISSION_EMAIL_UNVERIFIED: "יש לאמת את כתובת האימייל.",
  PERMISSION_DEALER_UNVERIFIED: "החשבון ממתין לאישור.",
  PERMISSION_PRIVACY_INCOMPLETE: "יש להשלים את מסך הפרטיות ו־AI.",
  PERMISSION_ACCOUNT_SUSPENDED: "החשבון מושעה.",
  PERMISSION_DEALER_DISABLED: "חשבון הסוחר אינו פעיל.",
  PERMISSION_FORBIDDEN: "אין הרשאה לפעולה הזו.",
  PERMISSION_REAUTH_REQUIRED: "נדרש אימות מחדש.",
  IDENTITY_LINK_REQUIRED: "קיים חשבון עם האימייל הזה — התחבר בסיסמה כדי לקשר.",
  IDENTITY_PROVIDER_TAKEN: "חשבון הספק כבר מקושר למשתמש אחר.",
  RESOURCE_NOT_FOUND: "הפריט לא נמצא.",
  RESOURCE_CONFLICT: "לא ניתן להשלים את הפעולה במצב הנוכחי.",
  MATCH_VEHICLE_UNAVAILABLE: "הרכב אינו זמין יותר.",
  MATCH_STALE_OPPORTUNITY: "ההזדמנות אינה בתוקף.",
  RATE_LIMIT_EXCEEDED: "יותר מדי ניסיונות. נסה שוב בעוד רגע.",
  ENTITLEMENT_REQUIRED: "נדרש מנוי פעיל.",
  REVEAL_ALLOWANCE_EXHAUSTED: "אין חיבורים זמינים.",
  SERVER_INTERNAL: "שגיאה זמנית. נסה שוב.",
  AGENT_UNAVAILABLE: "הסוכן אינו זמין כרגע.",
  AGENT_TIMEOUT: "הסוכן לא הספיק לענות.",
  MEDIA_UNAVAILABLE: "לא ניתן לטעון את הקובץ.",
};

export type V1ErrorBody = {
  error: {
    code: V1ErrorCode;
    message: string;
    requestId: string;
  };
};

export function v1ErrorBody(
  code: V1ErrorCode,
  requestId: string,
  message?: string
): V1ErrorBody {
  return {
    error: {
      code,
      message: message ?? DEFAULT_MESSAGE_HE[code],
      requestId,
    },
  };
}

export function httpStatusForCode(code: V1ErrorCode): number {
  return V1_STATUS_BY_CODE[code];
}
